import Footer from '@/components/Footer';
import NavBar from '@/components/NavBar';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../globals.css';

const minerva = localFont({
  src: [
    {
      path: '../../../public/fonts/minerva.woff2',
      style: 'normal',
    },
  ],
  variable: '--font-minerva',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${minerva.variable} antialiased flex flex-col h-dvh`}>
        <div className='flex-1 w-full'>
          <NavBar />
          <div className='max-w-screen-xl w-11/12 mx-auto flex flex-col sm:flex-row'>
            <main className='p-8 shadow-lg bg-white rounded sm:grow overflow-hidden'>{children}</main>
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
